# Generated by Django 4.2.1 on 2023-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_disliked_post_liked'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved',
        ),
        migrations.AddField(
            model_name='user',
            name='liked_post',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_post', to='blog.post', verbose_name='Лайкнуті'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_post',
            field=models.ManyToManyField(blank=True, default=None, related_name='saved_post', to='blog.post', verbose_name='Збережені'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.IntegerField(blank=True, default=0, verbose_name='Підписників'),
        ),
    ]
