# Generated by Django 4.2.1 on 2023-11-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_theme_options_alter_post_is_active_and_more'),
        ('users', '0002_remove_user_liked_remove_user_saved_user_liked_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_post',
            field=models.ManyToManyField(blank=True, default=None, related_name='disliked_post', to='blog.post', verbose_name='Дізлайкнуті'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
