# Generated by Django 4.2.1 on 2023-11-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_subscribers_user_subscribes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.IntegerField(blank=True, default=0, verbose_name='Підписники'),
        ),
    ]
