# Generated by Django 4.2.1 on 2023-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disliked',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кількість дизлайків'),
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кількість лайків'),
        ),
    ]
